import 'package:flutter/foundation.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'dart:io';

class PDFService {
  Future<String?> createDocument({
    required String title,
    required String content,
    String? author,
  }) async {
    try {
      final pdf = pw.Document();

      pdf.addPage(
        pw.Page(
          build: (pw.Context context) {
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Header(
                  level: 0,
                  child: pw.Text(
                    title,
                    style: pw.TextStyle(
                      fontSize: 24,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                ),
                if (author != null)
                  pw.Padding(
                    padding: const pw.EdgeInsets.only(top: 10, bottom: 20),
                    child: pw.Text(
                      'Author: $author',
                      style: pw.TextStyle(
                        fontSize: 12,
                        color: PdfColors.grey,
                      ),
                    ),
                  ),
                pw.Paragraph(
                  text: content,
                  style: pw.TextStyle(fontSize: 14),
                ),
                pw.Footer(
                  trailing: pw.Text(
                    'Generated by AC AI',
                    style: pw.TextStyle(
                      fontSize: 10,
                      color: PdfColors.grey,
                    ),
                  ),
                ),
              ],
            );
          },
        ),
      );

      final file = File('/sdcard/Download/$title.pdf');
      await file.writeAsBytes(await pdf.save());
      
      debugPrint('PDF created: ${file.path}');
      return file.path;
    } catch (e) {
      debugPrint('PDF creation error: $e');
      return null;
    }
  }

  Future<bool> printDocument(String filePath) async {
    try {
      final file = File(filePath);
      if (!await file.exists()) return false;

      await Printing.layoutPdf(
        onLayout: (format) async => file.readAsBytesSync(),
      );
      
      debugPrint('PDF printed: $filePath');
      return true;
    } catch (e) {
      debugPrint('Print error: $e');
      return false;
    }
  }

  Future<bool> sharePDF(String filePath) async {
    try {
      await Printing.sharePdf(
        bytes: await File(filePath).readAsBytes(),
        filename: filePath.split('/').last,
      );
      
      debugPrint('PDF shared: $filePath');
      return true;
    } catch (e) {
      debugPrint('Share error: $e');
      return false;
    }
  }

  void dispose() {
    debugPrint('PDF Service disposed');
  }
}
