import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:flutter/foundation.dart';

class PDFService {
  String _lastPdfPath = '';
  bool _isGenerating = false;

  String get lastPdfPath => _lastPdfPath;
  bool get isGenerating => _isGenerating;

  Future<String?> createPdf({
    required String title,
    required String content,
    String? author,
  }) async {
    if (_isGenerating) {
      debugPrint('PDF already being generated');
      return null;
    }

    try {
      _isGenerating = true;
      debugPrint('Generating PDF: $title');

      final pdf = pw.Document(
        title: title,
        author: author ?? 'AC AI',
      );

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          build: (pw.Context context) {
            return [
              pw.Header(
                level: 0,
                child: pw.Text(
                  title,
                  style: pw.TextStyle(
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Paragraph(
                text: content,
                style: const pw.TextStyle(fontSize: 12, lineSpacing: 4),
              ),
              pw.SizedBox(height: 20),
              pw.Footer(
                title: pw.Text(
                  'Generated by AC AI - ${DateTime.now().toString()}',
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey,
                  ),
                ),
              ),
            ];
          },
        ),
      );

      final dir = await getApplicationDocumentsDirectory();
      final fileName = '${title.replaceAll(' ', '_')}_${DateTime.now().millisecondsSinceEpoch}.pdf';
      final file = File('${dir.path}/$fileName');
      await file.writeAsBytes(await pdf.save());

      _lastPdfPath = file.path;
      _isGenerating = false;

      debugPrint('PDF created: ${file.path}');
      return file.path;
    } catch (e) {
      _isGenerating = false;
      debugPrint('PDF creation error: $e');
      return null;
    }
  }

  Future<String?> createPdfFromList({
    required String title,
    required List<String> items,
  }) async {
    final content = items.map((item) => '• $item').join('\n');
    return await createPdf(title: title, content: content);
  }

  Future<String?> createReport({
    required String title,
    required Map<String, String> data,
  }) async {
    final content = data.entries
        .map((entry) => '${entry.key}: ${entry.value}')
        .join('\n');
    return await createPdf(title: title, content: content);
  }

  void dispose() {
    debugPrint('PDF Service disposed');
  }
}
